import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import App from "../components/App/App";
import { AuthContext } from "../context/Auth";

const Home = () => {
  const router = useRouter();
  const { currentUser } = useContext(AuthContext);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (!currentUser) {
      router.push("/register");
    }
    if (currentUser) {
      setIsLoading(false);
    }
  }, [router, currentUser]);

  if (!currentUser) {
    return router.push("/register");
  }
  if (currentUser && !isLoading) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <App />
      </div>
    );
  }

  if (isLoading) {
    return (
      <>
        <p>Loadning...</p>
      </>
    );
  }
};

export default Home;
